version: '3.8'
services:
  backend:
    build:
      context: ./Backend
      #dockerfile: ../src/main/java/Dockerfile
      dockerfile: Dockerfile
    image: backend:2.0
    container_name: backend-container
    ports:
      - "8082:8082"
    networks:
      - app-network
    volumes:
      - ./data.txt:/app/data.txt
    restart: always

  frontend:
    build:
      context: ./Frontend
      #dockerfile: ../src/main/resources/Dockerfile
      dockerfile: Dockerfile
    image: frontend:2.0
    container_name: frontend-container
    ports:
      - "8081:8081"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
